name: Common Steps
description: Configure common steps

runs:
  using: "composite"
  steps:
    - name: Configure environment
      shell: bash
      run: |-
        echo "running on branch $GITHUB_REF"
        echo "TARGET_ENV=dev" >> $GITHUB_ENV

#    - name: Load secrets
#      id: secrets
#      uses: google-github-actions/get-secretmanager-secrets@v1
#      with:
#        secrets: |-
#          PG_ADMIN_PASSWORD: ${{ inputs.GOOGLE_PROJECT }}/PG_ADMIN_PASSWORD
#          MONGODB_PASSWORD: ${{ inputs.GOOGLE_PROJECT }}/MONGODB_PASSWORD

    - name: Configure Docker to use GCP Artifact Registry
      shell: bash
      run: |-
        gcloud auth configure-docker us-central1-docker.pkg.dev

