name: 'Docker Build'
description: 'docker build'

inputs:
  IMG_NAME:
    description: image name
    required: true
  IMG_TAG:
    description: image tag
    required: true
  ARTIFACTORY_URL:
    description: Artifactory url
    required: true
  ARTIFACTORY_NAMESPACE:
    description: image namespace
    required: true
  BUILD_TYPE:
    required: false
    default: "RELEASE"
    description: Artifactory namespace

runs:
  using: composite
  steps:
    - name: Docker build
      id: docker-build
      shell: bash
      run: |-
        ls -al
        
        echo "SNAPSHOT version move from target folder to home path and rename the jar"
        if [ -z "${{ inputs.IMG_TAG }}" ]; then
          NEW_IMG_TAG=$(git rev-parse --short HEAD)
        fi
        echo "Using NEW_IMG_TAG = $NEW_IMG_TAG"
        
        echo "Starting Build"
        docker build -t ${{ inputs.ARTIFACTORY_URL }}/${{ inputs.ARTIFACTORY_NAMESPACE }}/${{ inputs.IMG_NAME }}:$NEW_IMG_TAG .
        
        echo "Push to artifactory"
        docker push ${{ inputs.ARTIFACTORY_URL }}/${{ inputs.ARTIFACTORY_NAMESPACE }}/${{ inputs.IMG_NAME }}:$NEW_IMG_TAG
        
        echo "Docker CleanUp"
        docker rmi ${{ inputs.ARTIFACTORY_URL }}/${{ inputs.ARTIFACTORY_NAMESPACE }}/${{ inputs.IMG_NAME }}:$NEW_IMG_TAG
        
        echo "NEW_IMG_TAG=$NEW_IMG_TAG" >> $GITHUB_OUTPUT
        echo "NEW_IMG_URL=${{ inputs.ARTIFACTORY_URL }}/${{ inputs.ARTIFACTORY_NAMESPACE }}/${{ inputs.IMG_NAME }}:$NEW_IMG_TAG" >> $GITHUB_OUTPUT
        cat $GITHUB_ENV