name: 'Docker Build'
description: 'docker build'

inputs:
  IMG_NAME:
    description: image name
    required: true
  IMG_TAG:
    description: image tag
    required: true
  ARTIFACTORY_URL:
    description: Artifactory url
    required: true
  ARTIFACTORY_NAMESPACE:
    description: image namespace
    required: true
  BUILD_TYPE:
    required: false
    default: "RELEASE"
    description: Artifactory namespace

runs:
  using: composite
  steps:
    - name: Docker build
      id: docker-build
      shell: bash
      run: |-
        ls -al
        echo "Starting Build"
        docker build -t ${{ inputs.ARTIFACTORY_URL }}/${{ inputs.ARTIFACTORY_NAMESPACE }}/${{ inputs.IMG_NAME }}:${{ inputs.IMG_TAG }} .
        
        echo "Push to artifactory"
        docker push ${{ inputs.ARTIFACTORY_URL }}/${{ inputs.ARTIFACTORY_NAMESPACE }}/${{ inputs.IMG_NAME }}:${{ inputs.IMG_TAG }}
        
        echo "Docker CleanUp"
        docker rmi ${{ inputs.ARTIFACTORY_URL }}/${{ inputs.ARTIFACTORY_NAMESPACE }}/${{ inputs.IMG_NAME }}:${{ inputs.IMG_TAG }}
