name: 'GKE Deploy'
description: 'GKE Deploy'
inputs:
  IMG_NAME:
    description: image name
    required: true
  IMG_TAG:
    description: image tag
    required: true
  ARTIFACTORY_URL:
    description: Artifactory url
    required: true
    default: ${ARTIFACTORY_URL}
  ARTIFACTORY_NAMESPACE:
    description: image namespace
    required: true
    default: ${ARTIFACTORY_NAMESPACE}
  RELEASE:
    description: Helm release
    required: true
  GKE_NAMESPACE:
    description: gke namespace
    required: true
  HELM_BIN:
    required: true
    description: Path to helm binary
  IMG_URL:
    required: true
    description: Whole Image URL with TAG

runs:
  using: composite
  steps:
    - name: Create namespace if it doesn't exist
      shell: bash
      run: |
        kubectl get namespace ${{ inputs.GKE_NAMESPACE }} >/dev/null 2>&1 || \
          kubectl create namespace ${{ inputs.GKE_NAMESPACE }}
    - name: Wait for CRD Schema Registration (10s)
      shell: bash
      run: |
        CRD_ES="externalsecrets.external-secrets.io"
        CRD_CSS="clustersecretstores.external-secrets.io"
        TIMEOUT="10s"

        echo "Waiting up to ${TIMEOUT} for ExternalSecret CRD (${CRD_ES}) to be established..."
        kubectl wait --for=condition=Established --timeout=${TIMEOUT} crd/${CRD_ES} || { 
            echo "Warning: CRD ${CRD_ES} not ready in ${TIMEOUT}. Proceeding with potential validation risk."
        }

        echo "Waiting up to ${TIMEOUT} for ClusterSecretStore CRD (${CRD_CSS}) to be established..."
        kubectl wait --for=condition=Established --timeout=${TIMEOUT} crd/${CRD_CSS} || { 
            echo "Warning: CRD ${CRD_CSS} not ready in ${TIMEOUT}. Proceeding with potential validation risk."
        }

        # CRUCIAL: Add a short pause to ensure the client's API discovery cache is updated.
        echo "CRDs reported ready. Waiting 3 seconds for client cache propagation..."
        sleep 3

    - name: Deploy via helm
      shell: bash
      run: |
        CHART_PATH=./${{ env.APPLICATION_NAME }}-helm
        "${{ inputs.HELM_BIN}}" upgrade \
            --install -f ${{ env.APPLICATION_NAME }}-helm/values.yaml ${{ inputs.RELEASE }} $CHART_PATH \
            --set namespace=${{ inputs.GKE_NAMESPACE }} \
            --set env="dev" \
            --wait \
            --timeout 10m \
            --disable-openapi-validation

    - name: Verify Deployment
      id: verify
      shell: bash
      run: |
        kubectl get all -n ${{ inputs.GKE_NAMESPACE }}
        kubectl cluster-info
        sleep 10
        echo "View Pods in namespace ${{ inputs.GKE_NAMESPACE }}"
        kubectl get pods -n ${{ inputs.GKE_NAMESPACE }}