name: 'GKE Deploy'
description: 'GKE Deploy'
inputs:
  IMG_NAME:
    description: image name
    required: true
  IMG_TAG:
    description: image tag
    required: true
  ARTIFACTORY_URL:
    description: Artifactory url
    required: true
    default: ${ARTIFACTORY_URL}
  ARTIFACTORY_NAMESPACE:
    description: image namespace
    required: true
    default: ${ARTIFACTORY_NAMESPACE}
  RELEASE:
    description: Helm release
    required: true
  GKE_NAMESPACE:
    description: gke namespace
    required: true
  HELM_BIN:
    required: true
    description: Path to helm binary
  IMG_URL:
    required: true
    description: Whole Image URL with TAG

runs:
  using: composite
  steps:
    - name: Create namespace if it doesn't exist
      shell: bash
      run: |
        kubectl get namespace $GKE_NAMESPACE >/dev/null 2>&1 || \
          kubectl create namespace $GKE_NAMESPACE

    - name: Deploy via helm
      shell: bash
      run: |
        CHART_PATH=./${{ env.APPLICATION_NAME }}-helm
        "${{ HELM_BIN}}" upgrade \
            --install -f ${{ env.APPLICATION_NAME }}-helm/values.yaml $RELEASE $CHART_PATH \
            --set namespace=${{ GKE_NAMESPACE }}
            --set env="dev"
            --wait \
            --timeout 10m

    - name: Verify Deployment
      id: verify
      shell: bash
      run: |
        kubectl get all -n ${{ GKE_NAMESPACE }}
        kubectl cluster-info
        sleep 10
        echo "View Pods in namespace ${{ GKE_NAMESPACE }}"
        kubectl get pods -n ${{ GKE_NAMESPACE }}